version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: husky
    versions:
    - ">=5.0.0"
  - dependency-name: karma-webpack
    versions:
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.16
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: es-check
    versions:
    - 5.2.1
  registries:
  - npm-registry-registry-npmjs-org
